#!/bin/bash
echo 'Iniciando o build de todas as imagens da ONG...'
echo '=== Buildando minha-ong/moodle:1.0 ==='
sg docker -c 'docker build -t minha-ong/moodle:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/moodle'
echo '=== Buildando minha-ong/metabase:1.0 ==='
sg docker -c 'docker build -t minha-ong/metabase:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/metabase'
echo '=== Buildando minha-ong/superset:1.0 ==='
sg docker -c 'docker build -t minha-ong/superset:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/superset'
echo '=== Buildando minha-ong/postgres:1.0 ==='
sg docker -c 'docker build -t minha-ong/postgres:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/postgres'
echo '=== Buildando minha-ong/mariadb:1.0 ==='
sg docker -c 'docker build -t minha-ong/mariadb:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/mariadb'
echo '=== Buildando minha-ong/redis:1.0 ==='
sg docker -c 'docker build -t minha-ong/redis:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/redis'
echo '=== Buildando minha-ong/n8n:1.0 ==='
sg docker -c 'docker build -t minha-ong/n8n:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/n8n'
echo '=== Buildando minha-ong/node-red:1.0 ==='
sg docker -c 'docker build -t minha-ong/node-red:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/node-red'
echo '=== Buildando minha-ong/rabbitmq:1.0 ==='
sg docker -c 'docker build -t minha-ong/rabbitmq:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/rabbitmq'
echo '=== Buildando minha-ong/wiki:1.0 ==='
sg docker -c 'docker build -t minha-ong/wiki:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/wiki'
echo '=== Buildando minha-ong/nextcloud:1.0 ==='
sg docker -c 'docker build -t minha-ong/nextcloud:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/nextcloud'
echo '=== Buildando minha-ong/focalboard:1.0 ==='
sg docker -c 'docker build -t minha-ong/focalboard:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/focalboard'
echo '=== Buildando minha-ong/nginx-proxy-manager:1.0 ==='
sg docker -c 'docker build -t minha-ong/nginx-proxy-manager:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/nginx-proxy-manager'
echo '=== Buildando minha-ong/portainer:1.0 ==='
sg docker -c 'docker build -t minha-ong/portainer:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/portainer'
echo '=== Buildando minha-ong/uptime-kuma:1.0 ==='
sg docker -c 'docker build -t minha-ong/uptime-kuma:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/uptime-kuma'
echo '=== Buildando minha-ong/vaultwarden:1.0 ==='
sg docker -c 'docker build -t minha-ong/vaultwarden:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/vaultwarden'
echo '=== Buildando minha-ong/grafana:1.0 ==='
sg docker -c 'docker build -t minha-ong/grafana:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/grafana'
echo '=== Buildando minha-ong/chatwoot:1.0 ==='
sg docker -c 'docker build -t minha-ong/chatwoot:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/chatwoot'
echo '=== Buildando minha-ong/glpi:1.0 ==='
sg docker -c 'docker build -t minha-ong/glpi:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/glpi'
echo '=== Buildando minha-ong/rocket-chat:1.0 ==='
sg docker -c 'docker build -t minha-ong/rocket-chat:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/rocket-chat'
echo '=== Buildando minha-ong/wordpress:1.0 ==='
sg docker -c 'docker build -t minha-ong/wordpress:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/wordpress'
echo '=== Buildando minha-ong/ghost:1.0 ==='
sg docker -c 'docker build -t minha-ong/ghost:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/ghost'
echo '=== Buildando minha-ong/odoo:1.0 ==='
sg docker -c 'docker build -t minha-ong/odoo:1.0 /home/vier/Documentos/Code/docker/Imagens/catalogo-ong/odoo'
