version: "3.8"
services:
  grafana:
    image: gttransformadigital/grafana:1.0
    container_name: gttransformadigital-grafana
    restart: always
    networks:
      - gttransformadigital-net
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
networks:
  gttransformadigital-net:
    driver: bridge
volumes:
  grafana_data:
