version: "3.8"
services:
  uptime-kuma:
    image: gttransformadigital/uptime-kuma:1.0
    container_name: gttransformadigital-uptime-kuma
    restart: always
    networks:
      - gttransformadigital-net
    ports:
      - "3001:3001"
    volumes:
      - kuma_data:/app/data
networks:
  gttransformadigital-net:
    driver: bridge
volumes:
  kuma_data:
