version: "3.8"
services:
  chatwoot:
    image: gttransformadigital/chatwoot:1.0
    container_name: gttransformadigital-chatwoot
    restart: always
    networks:
      - gttransformadigital-net
networks:
  gttransformadigital-net:
    driver: bridge
